apiVersion: v1
kind: Pod
metadata:
  labels:
  name: nginx-storage
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - mountPath: /app/data
          name: mealie-data
    - image: busybox
      name: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 1000"]
      volumeMounts:
        - mountPath: /app/data
          name: mealie-data
  volumes:
    - name: mealie-data
      persistentVolumeClaim:
        claimName: mealie-data


